// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqq1BbzsUSMIjSe39VRq2VOVmuyc5bF98',
    appId: '1:971738476715:web:c600fd0b85fcf70202c7ee',
    messagingSenderId: '971738476715',
    projectId: 'caffeine-cafe-47df1',
    authDomain: 'caffeine-cafe-47df1.firebaseapp.com',
    storageBucket: 'caffeine-cafe-47df1.firebasestorage.app',
    measurementId: 'G-R53CDWSYV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAjlavLONh6qPL1rjLo99fuq243wNLHAU',
    appId: '1:971738476715:android:0460e798d7d4f18402c7ee',
    messagingSenderId: '971738476715',
    projectId: 'caffeine-cafe-47df1',
    storageBucket: 'caffeine-cafe-47df1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7pbO34z6HMlLZyvEIPRuTwd1XqiJa3wU',
    appId: '1:971738476715:ios:37cb50ab4230c6fa02c7ee',
    messagingSenderId: '971738476715',
    projectId: 'caffeine-cafe-47df1',
    storageBucket: 'caffeine-cafe-47df1.firebasestorage.app',
    iosBundleId: 'com.example.caffeine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7pbO34z6HMlLZyvEIPRuTwd1XqiJa3wU',
    appId: '1:971738476715:ios:37cb50ab4230c6fa02c7ee',
    messagingSenderId: '971738476715',
    projectId: 'caffeine-cafe-47df1',
    storageBucket: 'caffeine-cafe-47df1.firebasestorage.app',
    iosBundleId: 'com.example.caffeine',
  );
}
